export const MOUSE_ENTER_SHOW = 'home/mouse_enter_show'
export const MOUSE_LEAVE_NOT_SHOW = 'home/mouse_leave_not_show'
export const CHANGE_HOME_DATA = 'home/change_home_data'
export const ADD_ARTICLE_LIST = 'home/add_article_list'
export const TOGGLE_SHOW_TOP = 'home/toggle_show_top'